version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - t2-server

  t2-server:
    container_name: t2-server
    build:
      context: .
      args:
        NODE_ENV: production
        MODE: production
    environment:
      - MODE=production
      - NODE_ENV=production
      - PORT=8000
      - GITHUB_ID=${GITHUB_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URI=${REDIS_URI}
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

  redis:
    container_name: t2-redis
    image: redis
    restart: always
    environment:
      REDIS_URI: redis://default:password@redis:6379
    volumes:
      - t2site_redis_volume_data:/var/lib/redis/data
    ports:
      - 6378:6379

  db:
    image: postgres:14
    container_name: t2-db
    restart: always
    ports:
      - '127.0.0.1:5435:5432'
    volumes:
      - ./t2sitepgdata:/var/lib/postgresql/data
      - t2site-pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: t2site

volumes:
  t2site-pg-data:
  t2site_redis_volume_data: